### ISSUE TITLE
Prepare Solidus Reports for Solidus 3.0

### ISSUE THREAD

**Issue by kennyadsl** [solidusio-contrib/solidus_reports#29]
Update this extension so that it works with Solidus 3.0 by making sure the specs pass.

**Comment by derrickp** [comment]
I can take this one. Easy since all of the specs pass on 3.0 without anything being done!

**Comment by derrickp** [comment]
Not sure if I should just move it to the final step or not. Let me know!

**Comment by kennyadsl** [comment]
Yeah, thanks!
